=== mrc-ide/grout/schema/RegionMetadata.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "bounds": {
        "type": "object",
        "properties": {
          "min": { "$ref": "#/$defs/lat-lng" },
          "max": { "$ref": "#/$defs/lat-lng" }
        },
        "additionalProperties": false,
        "required": [
          "min",
          "max"
        ]
      },
      "geojson_properties": { "type": "object" }
    },
    "additionalProperties": false,
    "required": [
      "id",
      "name",
      "bounds",
      "geojson_properties"
    ]
  },
  "$defs": {
    "lat-lng": {
      "type": "object",
      "properties": {
        "lat": { "type": "number" },
        "lng": { "type": "number" }
      },
      "additionalProperties": false,
      "required": ["lat", "lng"]
    }
  }
}

=== mrc-ide/grout/data/region_metadata/gadm41/admin1/region_metadata_CAN_1.json
[{"id":"CAN.1_1","name":"Alberta","bounds":{"min":{"lng":-120,"lat":49.0001},"max":{"lng":-110,"lat":60}},"geojson_properties":{"GID_1":"CAN.1_1","GID_0":"CAN","COUNTRY":"Canada","NAME_1":"Alberta","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Province","ENGTYPE_1":"Province","CC_1":"48","HASC_1":"CA.AB","ISO_1":"CA-AB"}},{"id":"CAN.2_1","name":"British Columbia","bounds":{"min":{"lng":-139.0522,"lat":48.3086},"max":{"lng":-114.0542,"lat":60}},"geojson_properties":{"GID_1":"CAN.2_1","GID_0":"CAN","COUNTRY":"Canada","NAME_1":"British Columbia","VARNAME_1":"Colombiebritannique|NewCaledon","NL_NAME_1":"NA","TYPE_1":"Province","ENGTYPE_1":"Province","CC_1":"59","HASC_1":"CA.BC","ISO_1":"CA-BC"}},{"id":"CAN.3_1","name":"Manitoba","bounds":{"min":{"lng":-102,"lat":49},"max":{"lng":-88.9672,"lat":60.0021}},"geojson_properties":{"GID_1":"CAN.3_1","GID_0":"CAN","COUNTRY":"Canada","NAME_1":"Manitoba","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Province","ENGTYPE_1":"Province","CC_1":"46","HASC_1":"CA.MB","ISO_1":"CA-MB"}},{"id":"CAN.4_1","name":"New Brunswick","bounds":{"min":{"lng":-69.0512,"lat":44.4833},"max":{"lng":-63.7711,"lat":48.0728}},"geojson_properties":{"GID_1":"CAN.4_1","GID_0":"CAN","COUNTRY":"Canada","NAME_1":"New Brunswick","VARNAME_1":"Nouveau-Brunswick|Acadia","NL_NAME_1":"NA","TYPE_1":"Province","ENGTYPE_1":"Province","CC_1":"13","HASC_1":"CA.NB","ISO_1":"CA-NB"}},{"id":"CAN.5_1","name":"Newfoundland and Labrador","bounds":{"min":{"lng":-67.8217,"lat":46.6103},"max":{"lng":-52.6189,"lat":62.4911}},"geojson_properties":{"GID_1":"CAN.5_1","GID_0":"CAN","COUNTRY":"Canada","NAME_1":"Newfoundland and Labrador","VARNAME_1":"Newfoundland|Terre-Neuve|Terre-N","NL_NAME_1":"NA","TYPE_1":"Province","ENGTYPE_1":"Province","CC_1":"10","HASC_1":"CA.NF","ISO_1":"CA-NL"}},{"id":"CAN.6_1","name":"Northwest Territories","bounds":{"min":{"lng":-136.4703,"lat":60},"max":{"lng":-102,"lat":78.7604}},"geojson_properties":{"GID_1":"CAN.6_1","GID_0":"CAN","COUNTRY":"Canada","NAME_1":"Northwest Territories","VARNAME_1":"TerritoiresduNord-Ouest","NL_NAME_1":"NA","TYPE_1":"Territoire","ENGTYPE_1":"Territory","CC_1":"61","HASC_1":"CA.NT","ISO_1":"CA-NT"}},{"id":"CAN.7_1","name":"Nova Scotia","bounds":{"min":{"lng":-66.3956,"lat":43.3889},"max":{"lng":-59.6428,"lat":47.2274}},"geojson_properties":{"GID_1":"CAN.7_1","GID_0":"CAN","COUNTRY":"Canada","NAME_1":"Nova Scotia","VARNAME_1":"Acadia|Nouvelle-Écosse","NL_NAME_1":"NA","TYPE_1":"Province","ENGTYPE_1":"Province","CC_1":"12","HASC_1":"CA.NS","ISO_1":"CA-NS"}},{"id":"CAN.8_1","name":"Nunavut","bounds":{"min":{"lng":-121.0492,"lat":56.4831},"max":{"lng":-61.0901,"lat":83.1104}},"geojson_properties":{"GID_1":"CAN.8_1","GID_0":"CAN","COUNTRY":"Canada","NAME_1":"Nunavut","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Territoire","ENGTYPE_1":"Territory","CC_1":"62","HASC_1":"CA.NU","ISO_1":"CA-NU"}},{"id":"CAN.9_1","name":"Ontario","bounds":{"min":{"lng":-95.156,"lat":41.6769},"max":{"lng":-74.346,"lat":56.8695}},"geojson_properties":{"GID_1":"CAN.9_1","GID_0":"CAN","COUNTRY":"Canada","NAME_1":"Ontario","VARNAME_1":"UpperCanada","NL_NAME_1":"NA","TYPE_1":"Province","ENGTYPE_1":"Province","CC_1":"35","HASC_1":"CA.ON","ISO_1":"CA-ON"}},{"id":"CAN.10_1","name":"Prince Edward Island","bounds":{"min":{"lng":-64.4136,"lat":45.9489},"max":{"lng":-61.9714,"lat":47.0588}},"geojson_properties":{"GID_1":"CAN.10_1","GID_0":"CAN","COUNTRY":"Canada","NAME_1":"Prince Edward Island","VARNAME_1":"ÎledeSaint-Jean|ÎleduPrince-","NL_NAME_1":"NA","TYPE_1":"Province","ENGTYPE_1":"Province","CC_1":"11","HASC_1":"CA.PE","ISO_1":"CA-PE"}},{"id":"CAN.11_1","name":"Québec","bounds":{"min":{"lng":-80.9911,"lat":44.9908},"max":{"lng":-57.1055,"lat":63.6979}},"geojson_properties":{"GID_1":"CAN.11_1","GID_0":"CAN","COUNTRY":"Canada","NAME_1":"Québec","VARNAME_1":"LowerCanada","NL_NAME_1":"NA","TYPE_1":"Province","ENGTYPE_1":"Province","CC_1":"24","HASC_1":"CA.QC","ISO_1":"NA"}},{"id":"CAN.12_1","name":"Saskatchewan","bounds":{"min":{"lng":-110.0078,"lat":49},"max":{"lng":-101.3625,"lat":60}},"geojson_properties":{"GID_1":"CAN.12_1","GID_0":"CAN","COUNTRY":"Canada","NAME_1":"Saskatchewan","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Province","ENGTYPE_1":"Province","CC_1":"47","HASC_1":"CA.SK","ISO_1":"CA-SK"}},{"id":"CAN.13_1","name":"Yukon","bounds":{"min":{"lng":-141.0069,"lat":60},"max":{"lng":-123.7893,"lat":71.0771}},"geojson_properties":{"GID_1":"CAN.13_1","GID_0":"CAN","COUNTRY":"Canada","NAME_1":"Yukon","VARNAME_1":"YukonTerritory|TerritoireduYu","NL_NAME_1":"NA","TYPE_1":"Territoire","ENGTYPE_1":"Territory","CC_1":"60","HASC_1":"CA.YT","ISO_1":"CA-YT"}}]

=== mrc-ide/grout/data/region_metadata/gadm41/admin1/region_metadata_PSE_1.json
[{"id":"PSE.1_1","name":"Gaza","bounds":{"min":{"lng":34.2293,"lat":31.2236},"max":{"lng":34.5463,"lat":31.5944}},"geojson_properties":{"GID_1":"PSE.1_1","GID_0":"PSE","COUNTRY":"Palestine","NAME_1":"Gaza","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"District","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"PS.GZ","ISO_1":"PS-GZA"}},{"id":"PSE.2_1","name":"West Bank","bounds":{"min":{"lng":34.8839,"lat":31.3441},"max":{"lng":35.5755,"lat":32.5516}},"geojson_properties":{"GID_1":"PSE.2_1","GID_0":"PSE","COUNTRY":"Palestine","NAME_1":"West Bank","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"District","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"PS.WE","ISO_1":"NA"}}]

=== mrc-ide/grout/region_metadata/1/region_metadata_region_metadata_IMN_1.json
[{"id":"IMN.1_2","name":"Andreas","bounds":{"min":{"lng":-4.4981,"lat":54.3333},"max":{"lng":-4.4025,"lat":54.4046}},"geojson_properties":{"GID_1":"IMN.1_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Andreas","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"ParishDistrict","ENGTYPE_1":"ParishDistrict","CC_1":"NA","HASC_1":"IM.AY","ISO_1":"NA"}},{"id":"IMN.2_2","name":"Arbory & Rushen","bounds":{"min":{"lng":-4.8409,"lat":54.0365},"max":{"lng":-4.6614,"lat":54.1479}},"geojson_properties":{"GID_1":"IMN.2_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Arbory & Rushen","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"ParishDistrict","ENGTYPE_1":"ParishDistrict","CC_1":"NA","HASC_1":"IM.RU","ISO_1":"NA"}},{"id":"IMN.3_2","name":"Ballaugh","bounds":{"min":{"lng":-4.5747,"lat":54.2693},"max":{"lng":-4.5002,"lat":54.3429}},"geojson_properties":{"GID_1":"IMN.3_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Ballaugh","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"ParishDistrict","ENGTYPE_1":"ParishDistrict","CC_1":"NA","HASC_1":"IM.MC","ISO_1":"NA"}},{"id":"IMN.4_2","name":"Braddan","bounds":{"min":{"lng":-4.5664,"lat":54.1211},"max":{"lng":-4.4681,"lat":54.2665}},"geojson_properties":{"GID_1":"IMN.4_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Braddan","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"ParishDistrict","ENGTYPE_1":"ParishDistrict","CC_1":"NA","HASC_1":"IM.MD","ISO_1":"NA"}},{"id":"IMN.5_2","name":"Bride","bounds":{"min":{"lng":-4.4277,"lat":54.3491},"max":{"lng":-4.3603,"lat":54.4179}},"geojson_properties":{"GID_1":"IMN.5_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Bride","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"ParishDistrict","ENGTYPE_1":"ParishDistrict","CC_1":"NA","HASC_1":"IM.AY","ISO_1":"NA"}},{"id":"IMN.6_2","name":"Castletown","bounds":{"min":{"lng":-4.675,"lat":54.0674},"max":{"lng":-4.6332,"lat":54.0837}},"geojson_properties":{"GID_1":"IMN.6_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Castletown","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"TownDistrict","ENGTYPE_1":"TownDistrict","CC_1":"NA","HASC_1":"IM.RU","ISO_1":"NA"}},{"id":"IMN.7_2","name":"Douglas","bounds":{"min":{"lng":-4.5288,"lat":54.1375},"max":{"lng":-4.4598,"lat":54.1839}},"geojson_properties":{"GID_1":"IMN.7_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Douglas","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"TownDistrict","ENGTYPE_1":"TownDistrict","CC_1":"NA","HASC_1":"IM.MD","ISO_1":"NA"}},{"id":"IMN.8_2","name":"Garff","bounds":{"min":{"lng":-4.4733,"lat":54.1749},"max":{"lng":-4.3064,"lat":54.3183}},"geojson_properties":{"GID_1":"IMN.8_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Garff","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"ParishDistrict","ENGTYPE_1":"ParishDistrict","CC_1":"NA","HASC_1":"IM.GR","ISO_1":"NA"}},{"id":"IMN.9_2","name":"German","bounds":{"min":{"lng":-4.7004,"lat":54.1759},"max":{"lng":-4.5501,"lat":54.2655}},"geojson_properties":{"GID_1":"IMN.9_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"German","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"ParishDistrict","ENGTYPE_1":"ParishDistrict","CC_1":"NA","HASC_1":"IM.GB","ISO_1":"NA"}},{"id":"IMN.10_2","name":"Jurby","bounds":{"min":{"lng":-4.5542,"lat":54.3355},"max":{"lng":-4.4684,"lat":54.3857}},"geojson_properties":{"GID_1":"IMN.10_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Jurby","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"ParishDistrict","ENGTYPE_1":"ParishDistrict","CC_1":"NA","HASC_1":"IM.MC","ISO_1":"NA"}},{"id":"IMN.11_2","name":"Lezayre","bounds":{"min":{"lng":-4.5135,"lat":54.2415},"max":{"lng":-4.3814,"lat":54.3523}},"geojson_properties":{"GID_1":"IMN.11_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Lezayre","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"ParishDistrict","ENGTYPE_1":"ParishDistrict","CC_1":"NA","HASC_1":"IM.AY","ISO_1":"NA"}},{"id":"IMN.12_2","name":"Malew","bounds":{"min":{"lng":-4.6862,"lat":54.0537},"max":{"lng":-4.5864,"lat":54.1707}},"geojson_properties":{"GID_1":"IMN.12_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Malew","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"ParishDistrict","ENGTYPE_1":"ParishDistrict","CC_1":"NA","HASC_1":"IM.RU","ISO_1":"NA"}},{"id":"IMN.13_2","name":"Marown","bounds":{"min":{"lng":-4.6121,"lat":54.1461},"max":{"lng":-4.5251,"lat":54.2253}},"geojson_properties":{"GID_1":"IMN.13_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Marown","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"ParishDistrict","ENGTYPE_1":"ParishDistrict","CC_1":"NA","HASC_1":"IM.MD","ISO_1":"NA"}},{"id":"IMN.14_2","name":"Michael","bounds":{"min":{"lng":-4.6192,"lat":54.2329},"max":{"lng":-4.5035,"lat":54.319}},"geojson_properties":{"GID_1":"IMN.14_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Michael","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"District","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"IM.MC","ISO_1":"NA"}},{"id":"IMN.15_2","name":"Onchan","bounds":{"min":{"lng":-4.5136,"lat":54.1654},"max":{"lng":-4.4208,"lat":54.2303}},"geojson_properties":{"GID_1":"IMN.15_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Onchan","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"District","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"IM.MD","ISO_1":"NA"}},{"id":"IMN.16_2","name":"Patrick","bounds":{"min":{"lng":-4.7431,"lat":54.1359},"max":{"lng":-4.6035,"lat":54.2224}},"geojson_properties":{"GID_1":"IMN.16_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Patrick","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"ParishDistrict","ENGTYPE_1":"ParishDistrict","CC_1":"NA","HASC_1":"IM.GB","ISO_1":"NA"}},{"id":"IMN.17_2","name":"Peel","bounds":{"min":{"lng":-4.7058,"lat":54.2157},"max":{"lng":-4.674,"lat":54.2307}},"geojson_properties":{"GID_1":"IMN.17_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Peel","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"TownDistrict","ENGTYPE_1":"TownDistrict","CC_1":"NA","HASC_1":"IM.GB","ISO_1":"NA"}},{"id":"IMN.18_2","name":"Port Erin","bounds":{"min":{"lng":-4.7814,"lat":54.0799},"max":{"lng":-4.7469,"lat":54.1011}},"geojson_properties":{"GID_1":"IMN.18_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Port Erin","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"VillageDistrict","ENGTYPE_1":"VillageDistrict","CC_1":"NA","HASC_1":"IM.RU","ISO_1":"NA"}},{"id":"IMN.19_2","name":"Port Saint Mary","bounds":{"min":{"lng":-4.7536,"lat":54.0674},"max":{"lng":-4.7292,"lat":54.0853}},"geojson_properties":{"GID_1":"IMN.19_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Port Saint Mary","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"VillageDistrict","ENGTYPE_1":"VillageDistrict","CC_1":"NA","HASC_1":"IM.RU","ISO_1":"NA"}},{"id":"IMN.20_2","name":"Ramsey","bounds":{"min":{"lng":-4.4078,"lat":54.3131},"max":{"lng":-4.3708,"lat":54.3385}},"geojson_properties":{"GID_1":"IMN.20_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Ramsey","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"TownDistrict","ENGTYPE_1":"TownDistrict","CC_1":"NA","HASC_1":"IM.AY","ISO_1":"NA"}},{"id":"IMN.21_2","name":"Santon","bounds":{"min":{"lng":-4.604,"lat":54.0907},"max":{"lng":-4.5292,"lat":54.1507}},"geojson_properties":{"GID_1":"IMN.21_2","GID_0":"IMN","COUNTRY":"Isle of Man","NAME_1":"Santon","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"ParishDistrict","ENGTYPE_1":"ParishDistrict","CC_1":"NA","HASC_1":"IM.MD","ISO_1":"NA"}}]

=== mrc-ide/grout/region_metadata/gadm41/admin1/region_metadata_SMR_1.json
[{"id":"SMR.1_1","name":"Acquaviva","bounds":{"min":{"lng":12.401,"lat":43.9302},"max":{"lng":12.4375,"lat":43.9552}},"geojson_properties":{"GID_1":"SMR.1_1","GID_0":"SMR","COUNTRY":"San Marino","NAME_1":"Acquaviva","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Castello","ENGTYPE_1":"Municipality","CC_1":"NA","HASC_1":"SM.AC","ISO_1":"NA"}},{"id":"SMR.2_1","name":"Borgo Maggiore","bounds":{"min":{"lng":12.4255,"lat":43.9182},"max":{"lng":12.4802,"lat":43.9686}},"geojson_properties":{"GID_1":"SMR.2_1","GID_0":"SMR","COUNTRY":"San Marino","NAME_1":"Borgo Maggiore","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Castello","ENGTYPE_1":"Municipality","CC_1":"NA","HASC_1":"SM.BM","ISO_1":"NA"}},{"id":"SMR.3_1","name":"Chiesanuova","bounds":{"min":{"lng":12.4056,"lat":43.8984},"max":{"lng":12.4354,"lat":43.9291}},"geojson_properties":{"GID_1":"SMR.3_1","GID_0":"SMR","COUNTRY":"San Marino","NAME_1":"Chiesanuova","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Castello","ENGTYPE_1":"Municipality","CC_1":"NA","HASC_1":"SM.CH","ISO_1":"NA"}},{"id":"SMR.4_1","name":"Domagnano","bounds":{"min":{"lng":12.456,"lat":43.9391},"max":{"lng":12.5101,"lat":43.9685}},"geojson_properties":{"GID_1":"SMR.4_1","GID_0":"SMR","COUNTRY":"San Marino","NAME_1":"Domagnano","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Castello","ENGTYPE_1":"Municipality","CC_1":"NA","HASC_1":"SM.DO","ISO_1":"NA"}},{"id":"SMR.5_1","name":"Faetano","bounds":{"min":{"lng":12.4712,"lat":43.9174},"max":{"lng":12.514,"lat":43.956}},"geojson_properties":{"GID_1":"SMR.5_1","GID_0":"SMR","COUNTRY":"San Marino","NAME_1":"Faetano","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Castello","ENGTYPE_1":"Municipality","CC_1":"NA","HASC_1":"SM.FA","ISO_1":"SM-04"}},{"id":"SMR.6_1","name":"Fiorentino","bounds":{"min":{"lng":12.4293,"lat":43.8949},"max":{"lng":12.4756,"lat":43.9241}},"geojson_properties":{"GID_1":"SMR.6_1","GID_0":"SMR","COUNTRY":"San Marino","NAME_1":"Fiorentino","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Castello","ENGTYPE_1":"Municipality","CC_1":"NA","HASC_1":"SM.FI","ISO_1":"NA"}},{"id":"SMR.7_1","name":"Montegiardino","bounds":{"min":{"lng":12.4685,"lat":43.8987},"max":{"lng":12.4938,"lat":43.9232}},"geojson_properties":{"GID_1":"SMR.7_1","GID_0":"SMR","COUNTRY":"San Marino","NAME_1":"Montegiardino","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Castello","ENGTYPE_1":"Municipality","CC_1":"NA","HASC_1":"SM.MG","ISO_1":"NA"}},{"id":"SMR.8_1","name":"San Marino","bounds":{"min":{"lng":12.4127,"lat":43.9131},"max":{"lng":12.455,"lat":43.9435}},"geojson_properties":{"GID_1":"SMR.8_1","GID_0":"SMR","COUNTRY":"San Marino","NAME_1":"San Marino","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Castello","ENGTYPE_1":"Municipality","CC_1":"NA","HASC_1":"SM.SM","ISO_1":"NA"}},{"id":"SMR.9_1","name":"Serravalle","bounds":{"min":{"lng":12.4467,"lat":43.9581},"max":{"lng":12.5131,"lat":43.9955}},"geojson_properties":{"GID_1":"SMR.9_1","GID_0":"SMR","COUNTRY":"San Marino","NAME_1":"Serravalle","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Castello","ENGTYPE_1":"Municipality","CC_1":"NA","HASC_1":"SM.SE","ISO_1":"SM-09"}}]

=== mrc-ide/grout/region_metadata/gadm41/1/region_metadata_KWT_1.json
[{"id":"KWT.1_1","name":"Al Ahmadi","bounds":{"min":{"lng":47.4739,"lat":28.5244},"max":{"lng":48.654,"lat":29.2663}},"geojson_properties":{"GID_1":"KWT.1_1","GID_0":"KWT","COUNTRY":"Kuwait","NAME_1":"Al Ahmadi","VARNAME_1":"NA","NL_NAME_1":"الاحمدي","TYPE_1":"Muhafazah","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"KW.AH","ISO_1":"KW-AH"}},{"id":"KWT.2_1","name":"Al Farwaniyah","bounds":{"min":{"lng":47.8417,"lat":29.185},"max":{"lng":48.0346,"lat":29.3304}},"geojson_properties":{"GID_1":"KWT.2_1","GID_0":"KWT","COUNTRY":"Kuwait","NAME_1":"Al Farwaniyah","VARNAME_1":"Farwaniya","NL_NAME_1":"الفروانية‎","TYPE_1":"Muhafazah","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"KW.FA","ISO_1":"KW-FA"}},{"id":"KWT.3_1","name":"Al Jahrah","bounds":{"min":{"lng":46.5426,"lat":28.9911},"max":{"lng":48.4432,"lat":30.0839}},"geojson_properties":{"GID_1":"KWT.3_1","GID_0":"KWT","COUNTRY":"Kuwait","NAME_1":"Al Jahrah","VARNAME_1":"Jahra","NL_NAME_1":"الجهراء","TYPE_1":"Muhafazah","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"KW.JA","ISO_1":"NA"}},{"id":"KWT.4_1","name":"Al Kuwayt","bounds":{"min":{"lng":47.8596,"lat":29.31},"max":{"lng":48.0108,"lat":29.3935}},"geojson_properties":{"GID_1":"KWT.4_1","GID_0":"KWT","COUNTRY":"Kuwait","NAME_1":"Al Kuwayt","VARNAME_1":"AlAsimah,Capital,Kuwait","NL_NAME_1":"العاصمه","TYPE_1":"Muhafazah","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"KW.KU","ISO_1":"NA"}},{"id":"KWT.5_1","name":"Hawalli","bounds":{"min":{"lng":47.9797,"lat":29.3023},"max":{"lng":48.1018,"lat":29.3707}},"geojson_properties":{"GID_1":"KWT.5_1","GID_0":"KWT","COUNTRY":"Kuwait","NAME_1":"Hawalli","VARNAME_1":"Hawali,Howali","NL_NAME_1":"حولي","TYPE_1":"Muhafazah","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"KW.HW","ISO_1":"KW-HA"}},{"id":"KWT.6_1","name":"Mubarak Al-Kabeer","bounds":{"min":{"lng":48.004,"lat":29.2087},"max":{"lng":48.1074,"lat":29.3051}},"geojson_properties":{"GID_1":"KWT.6_1","GID_0":"KWT","COUNTRY":"Kuwait","NAME_1":"Mubarak Al-Kabeer","VARNAME_1":"NA","NL_NAME_1":"مباركالكبير","TYPE_1":"Muhafazah","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"KW.MU","ISO_1":"NA"}}]

=== mrc-ide/grout/region_metadata/gadm41/admin1/region_metadata_WLF_1.json
[{"id":"WLF.1_1","name":"Alo","bounds":{"min":{"lng":-178.1592,"lat":-14.3691},"max":{"lng":-177.9986,"lat":-14.2456}},"geojson_properties":{"GID_1":"WLF.1_1","GID_0":"WLF","COUNTRY":"Wallis and Futuna","NAME_1":"Alo","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Kingdom","ENGTYPE_1":"Kingdom","CC_1":"NA","HASC_1":"WF.AL","ISO_1":"NA"}},{"id":"WLF.2_1","name":"Singave","bounds":{"min":{"lng":-178.1825,"lat":-14.3282},"max":{"lng":-178.1344,"lat":-14.2389}},"geojson_properties":{"GID_1":"WLF.2_1","GID_0":"WLF","COUNTRY":"Wallis and Futuna","NAME_1":"Singave","VARNAME_1":"Sigave","NL_NAME_1":"NA","TYPE_1":"Kingdom","ENGTYPE_1":"Kingdom","CC_1":"NA","HASC_1":"WF.SI","ISO_1":"NA"}},{"id":"WLF.3_1","name":"Uvéa","bounds":{"min":{"lng":-176.2511,"lat":-13.3922},"max":{"lng":-176.1247,"lat":-13.1828}},"geojson_properties":{"GID_1":"WLF.3_1","GID_0":"WLF","COUNTRY":"Wallis and Futuna","NAME_1":"Uvéa","VARNAME_1":"MataUtu","NL_NAME_1":"NA","TYPE_1":"Kingdom","ENGTYPE_1":"Kingdom","CC_1":"NA","HASC_1":"WF.UV","ISO_1":"NA"}}]

=== mrc-ide/grout/data/region_metadata/gadm41/admin1/region_metadata_MAR_1.json
[{"id":"MAR.1_1","name":"Chaouia - Ouardigha","bounds":{"min":{"lng":-8.1232,"lat":32.3493},"max":{"lng":-5.9999,"lat":33.8304}},"geojson_properties":{"GID_1":"MAR.1_1","GID_0":"MAR","COUNTRY":"Morocco","NAME_1":"Chaouia - Ouardigha","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Region","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MA.CO","ISO_1":"NA"}},{"id":"MAR.2_1","name":"Doukkala - Abda","bounds":{"min":{"lng":-9.4354,"lat":31.6938},"max":{"lng":-7.9324,"lat":33.4585}},"geojson_properties":{"GID_1":"MAR.2_1","GID_0":"MAR","COUNTRY":"Morocco","NAME_1":"Doukkala - Abda","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Region","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MA.DA","ISO_1":"NA"}},{"id":"MAR.3_1","name":"Fès - Boulemane","bounds":{"min":{"lng":-5.4336,"lat":32.6238},"max":{"lng":-2.9691,"lat":34.3254}},"geojson_properties":{"GID_1":"MAR.3_1","GID_0":"MAR","COUNTRY":"Morocco","NAME_1":"Fès - Boulemane","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Region","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MA.FB","ISO_1":"NA"}},{"id":"MAR.4_1","name":"Gharb - Chrarda - Béni Hssen","bounds":{"min":{"lng":-6.7118,"lat":34.0956},"max":{"lng":-5.1467,"lat":34.988}},"geojson_properties":{"GID_1":"MAR.4_1","GID_0":"MAR","COUNTRY":"Morocco","NAME_1":"Gharb - Chrarda - Béni Hssen","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Region","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MA.GB","ISO_1":"NA"}},{"id":"MAR.5_1","name":"Grand Casablanca","bounds":{"min":{"lng":-7.8949,"lat":33.3194},"max":{"lng":-7.3456,"lat":33.7343}},"geojson_properties":{"GID_1":"MAR.5_1","GID_0":"MAR","COUNTRY":"Morocco","NAME_1":"Grand Casablanca","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Region","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MA.GC","ISO_1":"NA"}},{"id":"MAR.6_1","name":"Guelmim - Es-Semara","bounds":{"min":{"lng":-11.7752,"lat":27.6701},"max":{"lng":-6.3745,"lat":30.4125}},"geojson_properties":{"GID_1":"MAR.6_1","GID_0":"MAR","COUNTRY":"Morocco","NAME_1":"Guelmim - Es-Semara","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Region","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MA.GE","ISO_1":"NA"}},{"id":"MAR.7_1","name":"Laâyoune - Boujdour - Sakia El H","bounds":{"min":{"lng":-13.1679,"lat":27.6785},"max":{"lng":-11.4789,"lat":28.2151}},"geojson_properties":{"GID_1":"MAR.7_1","GID_0":"MAR","COUNTRY":"Morocco","NAME_1":"Laâyoune - Boujdour - Sakia El H","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Region","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MA.LB","ISO_1":"NA"}},{"id":"MAR.8_1","name":"Marrakech - Tensift - Al Haouz","bounds":{"min":{"lng":-9.8424,"lat":30.8092},"max":{"lng":-6.9757,"lat":32.8157}},"geojson_properties":{"GID_1":"MAR.8_1","GID_0":"MAR","COUNTRY":"Morocco","NAME_1":"Marrakech - Tensift - Al Haouz","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Region","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MA.MK","ISO_1":"NA"}},{"id":"MAR.9_1","name":"Meknès - Tafilalet","bounds":{"min":{"lng":-6.3978,"lat":30.0061},"max":{"lng":-3.244,"lat":34.268}},"geojson_properties":{"GID_1":"MAR.9_1","GID_0":"MAR","COUNTRY":"Morocco","NAME_1":"Meknès - Tafilalet","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Region","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MA.MT","ISO_1":"NA"}},{"id":"MAR.10_1","name":"Oriental","bounds":{"min":{"lng":-4.0591,"lat":31.7097},"max":{"lng":-0.9963,"lat":35.4401}},"geojson_properties":{"GID_1":"MAR.10_1","GID_0":"MAR","COUNTRY":"Morocco","NAME_1":"Oriental","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Region","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MA.OR","ISO_1":"NA"}},{"id":"MAR.11_1","name":"Rabat - Salé - Zemmour - Zaer","bounds":{"min":{"lng":-7.1268,"lat":33.1421},"max":{"lng":-5.7447,"lat":34.1874}},"geojson_properties":{"GID_1":"MAR.11_1","GID_0":"MAR","COUNTRY":"Morocco","NAME_1":"Rabat - Salé - Zemmour - Zaer","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Region","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MA.RZ","ISO_1":"NA"}},{"id":"MAR.12_1","name":"Souss - Massa - Draâ","bounds":{"min":{"lng":-10.4396,"lat":29.0319},"max":{"lng":-5.1176,"lat":32.0342}},"geojson_properties":{"GID_1":"MAR.12_1","GID_0":"MAR","COUNTRY":"Morocco","NAME_1":"Souss - Massa - Draâ","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Region","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MA.SM","ISO_1":"NA"}},{"id":"MAR.13_1","name":"Tadla - Azilal","bounds":{"min":{"lng":-7.2664,"lat":31.3566},"max":{"lng":-5.5007,"lat":32.7654}},"geojson_properties":{"GID_1":"MAR.13_1","GID_0":"MAR","COUNTRY":"Morocco","NAME_1":"Tadla - Azilal","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Region","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MA.TD","ISO_1":"NA"}},{"id":"MAR.14_1","name":"Tanger - Tétouan","bounds":{"min":{"lng":-6.2501,"lat":34.7146},"max":{"lng":-4.4526,"lat":35.9226}},"geojson_properties":{"GID_1":"MAR.14_1","GID_0":"MAR","COUNTRY":"Morocco","NAME_1":"Tanger - Tétouan","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Region","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MA.TO","ISO_1":"NA"}},{"id":"MAR.15_1","name":"Taza - Al Hoceima - Taounate","bounds":{"min":{"lng":-5.4888,"lat":33.5694},"max":{"lng":-2.9459,"lat":35.2621}},"geojson_properties":{"GID_1":"MAR.15_1","GID_0":"MAR","COUNTRY":"Morocco","NAME_1":"Taza - Al Hoceima - Taounate","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Region","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MA.TH","ISO_1":"NA"}}]

=== mrc-ide/grout/region_metadata/1/region_metadata_region_metadata_GRC_1.json
[{"id":"GRC.1_1","name":"Aegean","bounds":{"min":{"lng":24.0999,"lat":35.3387},"max":{"lng":29.6457,"lat":40.0368}},"geojson_properties":{"GID_1":"GRC.1_1","GID_0":"GRC","COUNTRY":"Greece","NAME_1":"Aegean","VARNAME_1":"NA","NL_NAME_1":"Αιγαίο","TYPE_1":"Apokentroménesdioikíseis","ENGTYPE_1":"Decentralizedadministration","CC_1":"NA","HASC_1":"GR.AI","ISO_1":"NA"}},{"id":"GRC.2_1","name":"Athos","bounds":{"min":{"lng":23.9926,"lat":40.114},"max":{"lng":24.3996,"lat":40.4543}},"geojson_properties":{"GID_1":"GRC.2_1","GID_0":"GRC","COUNTRY":"Greece","NAME_1":"Athos","VARNAME_1":"NA","NL_NAME_1":"Άθως","TYPE_1":"Apokentroménesdioikíseis","ENGTYPE_1":"Decentralizedadministration","CC_1":"NA","HASC_1":"GR.MA","ISO_1":"NA"}},{"id":"GRC.3_1","name":"Attica","bounds":{"min":{"lng":22.8915,"lat":35.8218},"max":{"lng":24.1051,"lat":38.3413}},"geojson_properties":{"GID_1":"GRC.3_1","GID_0":"GRC","COUNTRY":"Greece","NAME_1":"Attica","VARNAME_1":"NA","NL_NAME_1":"Αττική","TYPE_1":"Apokentroménesdioikíseis","ENGTYPE_1":"Decentralizedadministration","CC_1":"NA","HASC_1":"GR.AT","ISO_1":"NA"}},{"id":"GRC.4_1","name":"Crete","bounds":{"min":{"lng":23.4735,"lat":34.8007},"max":{"lng":26.3535,"lat":35.696}},"geojson_properties":{"GID_1":"GRC.4_1","GID_0":"GRC","COUNTRY":"Greece","NAME_1":"Crete","VARNAME_1":"NA","NL_NAME_1":"Κρήτη","TYPE_1":"Apokentroménesdioikíseis","ENGTYPE_1":"Decentralizedadministration","CC_1":"NA","HASC_1":"GR.CR","ISO_1":"NA"}},{"id":"GRC.5_1","name":"Epirus and Western Macedonia","bounds":{"min":{"lng":20.0072,"lat":38.9446},"max":{"lng":22.1936,"lat":40.9548}},"geojson_properties":{"GID_1":"GRC.5_1","GID_0":"GRC","COUNTRY":"Greece","NAME_1":"Epirus and Western Macedonia","VARNAME_1":"NA","NL_NAME_1":"ΉπειροςκαιΔυτικήΜακεδονία","TYPE_1":"Apokentroménesdioikíseis","ENGTYPE_1":"Decentralizedadministration","CC_1":"NA","HASC_1":"GR.EM","ISO_1":"NA"}},{"id":"GRC.6_1","name":"Macedonia and Thrace","bounds":{"min":{"lng":21.7025,"lat":39.9076},"max":{"lng":26.6418,"lat":41.748}},"geojson_properties":{"GID_1":"GRC.6_1","GID_0":"GRC","COUNTRY":"Greece","NAME_1":"Macedonia and Thrace","VARNAME_1":"NA","NL_NAME_1":"ΜακεδονίακαιΘράκη","TYPE_1":"Apokentroménesdioikíseis","ENGTYPE_1":"Decentralizedadministration","CC_1":"NA","HASC_1":"GR.MH","ISO_1":"NA"}},{"id":"GRC.7_1","name":"Peloponnese, Western Greece and","bounds":{"min":{"lng":19.3724,"lat":36.3851},"max":{"lng":23.4529,"lat":39.899}},"geojson_properties":{"GID_1":"GRC.7_1","GID_0":"GRC","COUNTRY":"Greece","NAME_1":"Peloponnese, Western Greece and","VARNAME_1":"NA","NL_NAME_1":"Πελοπόννησος,ΔυτικήΕλλάδακαι","TYPE_1":"Apokentroménesdioikíseis","ENGTYPE_1":"Decentralizedadministration","CC_1":"NA","HASC_1":"GR.PW","ISO_1":"NA"}},{"id":"GRC.8_1","name":"Thessaly and Central Greece","bounds":{"min":{"lng":21.1188,"lat":37.9304},"max":{"lng":24.6863,"lat":40.194}},"geojson_properties":{"GID_1":"GRC.8_1","GID_0":"GRC","COUNTRY":"Greece","NAME_1":"Thessaly and Central Greece","VARNAME_1":"NA","NL_NAME_1":"ΘεσσαλίακαιΣτερεάΕλλάδα","TYPE_1":"Apokentroménesdioikíseis","ENGTYPE_1":"Decentralizedadministration","CC_1":"NA","HASC_1":"GR.TC","ISO_1":"NA"}}]
