=== mrc-ide/grout/schema/RegionMetadata.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "bounds": {
        "type": "object",
        "properties": {
          "min": { "$ref": "#/$defs/lat-lng" },
          "max": { "$ref": "#/$defs/lat-lng" }
        },
        "additionalProperties": false,
        "required": [
          "min",
          "max"
        ]
      },
      "geojson_properties": { "type": "object" }
    },
    "additionalProperties": false,
    "required": [
      "id",
      "name",
      "bounds",
      "geojson_properties"
    ]
  },
  "$defs": {
    "lat-lng": {
      "type": "object",
      "properties": {
        "lat": { "type": "number" },
        "lng": { "type": "number" }
      },
      "additionalProperties": false,
      "required": ["lat", "lng"]
    }
  }
}

=== mrc-ide/grout/data/region_metadata/gadm41/admin1/region_metadata_BRA_1.json
[{"id":"BRA.1_1","name":"Acre","bounds":{"min":{"lng":-73.9897,"lat":-11.1452},"max":{"lng":-66.5888,"lat":-7.1142}},"geojson_properties":{"GID_1":"BRA.1_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Acre","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.AC","ISO_1":"BR-AC"}},{"id":"BRA.2_1","name":"Alagoas","bounds":{"min":{"lng":-38.2376,"lat":-10.5003},"max":{"lng":-35.1519,"lat":-8.8131}},"geojson_properties":{"GID_1":"BRA.2_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Alagoas","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.AL","ISO_1":"BR-AL"}},{"id":"BRA.3_1","name":"Amapá","bounds":{"min":{"lng":-54.8763,"lat":-1.2362},"max":{"lng":-49.8758,"lat":4.4749}},"geojson_properties":{"GID_1":"BRA.3_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Amapá","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.AP","ISO_1":"NA"}},{"id":"BRA.4_1","name":"Amazonas","bounds":{"min":{"lng":-73.7957,"lat":-9.818},"max":{"lng":-56.0976,"lat":2.2299}},"geojson_properties":{"GID_1":"BRA.4_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Amazonas","VARNAME_1":"Amazone","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.AM","ISO_1":"BR-AM"}},{"id":"BRA.5_1","name":"Bahia","bounds":{"min":{"lng":-46.5772,"lat":-18.3486},"max":{"lng":-37.3411,"lat":-8.5328}},"geojson_properties":{"GID_1":"BRA.5_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Bahia","VARNAME_1":"Ba¡a","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.BA","ISO_1":"BR-BA"}},{"id":"BRA.6_1","name":"Ceará","bounds":{"min":{"lng":-41.4235,"lat":-7.8582},"max":{"lng":-37.2527,"lat":-2.7843}},"geojson_properties":{"GID_1":"BRA.6_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Ceará","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.CE","ISO_1":"NA"}},{"id":"BRA.7_1","name":"Distrito Federal","bounds":{"min":{"lng":-48.2858,"lat":-16.05},"max":{"lng":-47.3085,"lat":-15.5018}},"geojson_properties":{"GID_1":"BRA.7_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Distrito Federal","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"DistritoFederal","ENGTYPE_1":"FederalDistrict","CC_1":"NA","HASC_1":"BR.DF","ISO_1":"BR-DF"}},{"id":"BRA.8_1","name":"Espírito Santo","bounds":{"min":{"lng":-41.8798,"lat":-21.3018},"max":{"lng":-28.8477,"lat":-17.8919}},"geojson_properties":{"GID_1":"BRA.8_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Espírito Santo","VARNAME_1":"EspirituSanto","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.ES","ISO_1":"NA"}},{"id":"BRA.9_1","name":"Goiás","bounds":{"min":{"lng":-53.2485,"lat":-19.4984},"max":{"lng":-45.9072,"lat":-12.3954}},"geojson_properties":{"GID_1":"BRA.9_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Goiás","VARNAME_1":"Goiáz|Goyáz","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.GO","ISO_1":"NA"}},{"id":"BRA.10_1","name":"Maranhão","bounds":{"min":{"lng":-48.7552,"lat":-10.2618},"max":{"lng":-41.7963,"lat":-1.0495}},"geojson_properties":{"GID_1":"BRA.10_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Maranhão","VARNAME_1":"SãoLuízdeMaranhão","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.MA","ISO_1":"NA"}},{"id":"BRA.12_1","name":"Mato Grosso","bounds":{"min":{"lng":-61.6333,"lat":-18.0416},"max":{"lng":-50.2248,"lat":-7.349}},"geojson_properties":{"GID_1":"BRA.12_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Mato Grosso","VARNAME_1":"MattoGrosso","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.MT","ISO_1":"BR-MT"}},{"id":"BRA.11_1","name":"Mato Grosso do Sul","bounds":{"min":{"lng":-58.1628,"lat":-24.0674},"max":{"lng":-50.9229,"lat":-17.1663}},"geojson_properties":{"GID_1":"BRA.11_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Mato Grosso do Sul","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.MS","ISO_1":"BR-MS"}},{"id":"BRA.13_1","name":"Minas Gerais","bounds":{"min":{"lng":-51.0459,"lat":-22.9228},"max":{"lng":-39.8568,"lat":-14.2332}},"geojson_properties":{"GID_1":"BRA.13_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Minas Gerais","VARNAME_1":"Minas|MinasGeraes","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.MG","ISO_1":"BR-MG"}},{"id":"BRA.14_1","name":"Pará","bounds":{"min":{"lng":-58.8983,"lat":-9.8412},"max":{"lng":-46.0615,"lat":2.6325}},"geojson_properties":{"GID_1":"BRA.14_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Pará","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.PA","ISO_1":"NA"}},{"id":"BRA.15_1","name":"Paraíba","bounds":{"min":{"lng":-38.7656,"lat":-8.303},"max":{"lng":-34.7931,"lat":-6.0266}},"geojson_properties":{"GID_1":"BRA.15_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Paraíba","VARNAME_1":"Parahyba","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.PB","ISO_1":"NA"}},{"id":"BRA.16_1","name":"Paraná","bounds":{"min":{"lng":-54.616,"lat":-26.7171},"max":{"lng":-48.0235,"lat":-22.5167}},"geojson_properties":{"GID_1":"BRA.16_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Paraná","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.PR","ISO_1":"NA"}},{"id":"BRA.17_1","name":"Pernambuco","bounds":{"min":{"lng":-41.3583,"lat":-9.4827},"max":{"lng":-32.3778,"lat":-3.8046}},"geojson_properties":{"GID_1":"BRA.17_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Pernambuco","VARNAME_1":"Pernambouc","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.PE","ISO_1":"BR-PE"}},{"id":"BRA.18_1","name":"Piauí","bounds":{"min":{"lng":-46.0282,"lat":-10.9288},"max":{"lng":-40.3705,"lat":-2.7504}},"geojson_properties":{"GID_1":"BRA.18_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Piauí","VARNAME_1":"Piauhy","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.PI","ISO_1":"NA"}},{"id":"BRA.19_1","name":"Rio de Janeiro","bounds":{"min":{"lng":-44.8889,"lat":-23.3689},"max":{"lng":-40.9579,"lat":-20.7632}},"geojson_properties":{"GID_1":"BRA.19_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Rio de Janeiro","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.RJ","ISO_1":"BR-RJ"}},{"id":"BRA.20_1","name":"Rio Grande do Norte","bounds":{"min":{"lng":-38.5821,"lat":-6.9827},"max":{"lng":-34.9685,"lat":-4.8164}},"geojson_properties":{"GID_1":"BRA.20_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Rio Grande do Norte","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.RN","ISO_1":"BR-RN"}},{"id":"BRA.21_1","name":"Rio Grande do Sul","bounds":{"min":{"lng":-57.6455,"lat":-33.7463},"max":{"lng":-49.6918,"lat":-27.0823}},"geojson_properties":{"GID_1":"BRA.21_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Rio Grande do Sul","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.RS","ISO_1":"BR-RS"}},{"id":"BRA.22_1","name":"Rondônia","bounds":{"min":{"lng":-66.8103,"lat":-13.6907},"max":{"lng":-59.7744,"lat":-7.9759}},"geojson_properties":{"GID_1":"BRA.22_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Rondônia","VARNAME_1":"Guaporé","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.RO","ISO_1":"NA"}},{"id":"BRA.23_1","name":"Roraima","bounds":{"min":{"lng":-64.825,"lat":-1.5806},"max":{"lng":-58.8918,"lat":5.2649}},"geojson_properties":{"GID_1":"BRA.23_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Roraima","VARNAME_1":"RioBranco","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.RR","ISO_1":"BR-RR"}},{"id":"BRA.24_1","name":"Santa Catarina","bounds":{"min":{"lng":-53.8371,"lat":-29.3551},"max":{"lng":-48.3279,"lat":-25.9558}},"geojson_properties":{"GID_1":"BRA.24_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Santa Catarina","VARNAME_1":"SantaCatharina","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.SC","ISO_1":"BR-SC"}},{"id":"BRA.25_1","name":"São Paulo","bounds":{"min":{"lng":-53.1099,"lat":-25.358},"max":{"lng":-44.1614,"lat":-19.7799}},"geojson_properties":{"GID_1":"BRA.25_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"São Paulo","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.SP","ISO_1":"NA"}},{"id":"BRA.26_1","name":"Sergipe","bounds":{"min":{"lng":-38.245,"lat":-11.5685},"max":{"lng":-36.3959,"lat":-9.515}},"geojson_properties":{"GID_1":"BRA.26_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Sergipe","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.SE","ISO_1":"BR-SE"}},{"id":"BRA.27_1","name":"Tocantins","bounds":{"min":{"lng":-50.7421,"lat":-13.4682},"max":{"lng":-45.6996,"lat":-5.1686}},"geojson_properties":{"GID_1":"BRA.27_1","GID_0":"BRA","COUNTRY":"Brazil","NAME_1":"Tocantins","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Estado","ENGTYPE_1":"State","CC_1":"NA","HASC_1":"BR.TO","ISO_1":"BR-TO"}}]

=== mrc-ide/grout/region_metadata/gadm41/1/region_metadata_NOR_1.json
[{"id":"NOR.1_1","name":"Akershus","bounds":{"min":{"lng":10.3247,"lat":59.4808},"max":{"lng":11.9273,"lat":60.5955}},"geojson_properties":{"GID_1":"NOR.1_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Akershus","VARNAME_1":"Akershusfylke","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.AK","ISO_1":"NA"}},{"id":"NOR.2_1","name":"Ãstfold","bounds":{"min":{"lng":10.5764,"lat":58.8764},"max":{"lng":11.9424,"lat":59.7885}},"geojson_properties":{"GID_1":"NOR.2_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Ãstfold","VARNAME_1":"Oestfoldfylke","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.OF","ISO_1":"NA"}},{"id":"NOR.3_1","name":"Aust-Agder","bounds":{"min":{"lng":6.8225,"lat":58.1079},"max":{"lng":9.366,"lat":59.678}},"geojson_properties":{"GID_1":"NOR.3_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Aust-Agder","VARNAME_1":"Aust-Agderfylke|Austur-Agðir|Ne","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.AA","ISO_1":"NA"}},{"id":"NOR.4_1","name":"Buskerud","bounds":{"min":{"lng":7.4645,"lat":59.4056},"max":{"lng":10.6192,"lat":61.0905}},"geojson_properties":{"GID_1":"NOR.4_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Buskerud","VARNAME_1":"Buskerudfylke","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.BU","ISO_1":"NA"}},{"id":"NOR.5_1","name":"Finnmark","bounds":{"min":{"lng":21.1755,"lat":68.5544},"max":{"lng":31.162,"lat":71.1813}},"geojson_properties":{"GID_1":"NOR.5_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Finnmark","VARNAME_1":"Finnmarkfylke|Finmarken|Finnmár","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.FI","ISO_1":"NA"}},{"id":"NOR.6_1","name":"Hedmark","bounds":{"min":{"lng":9.5848,"lat":59.842},"max":{"lng":12.875,"lat":62.6986}},"geojson_properties":{"GID_1":"NOR.6_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Hedmark","VARNAME_1":"Hedmarkfylke|Hedemarken|Heiðmör","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.HE","ISO_1":"NA"}},{"id":"NOR.7_1","name":"Hordaland","bounds":{"min":{"lng":3.9047,"lat":59.4867},"max":{"lng":7.7131,"lat":61.0334}},"geojson_properties":{"GID_1":"NOR.7_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Hordaland","VARNAME_1":"Hordalandfylke|Hörðaland|Søndre","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.HO","ISO_1":"NA"}},{"id":"NOR.8_1","name":"Møre og Romsdal","bounds":{"min":{"lng":5.3438,"lat":61.9515},"max":{"lng":9.5851,"lat":63.5307}},"geojson_properties":{"GID_1":"NOR.8_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Møre og Romsdal","VARNAME_1":"MoereogRomsdalfylk|Møre|Romsd","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.MR","ISO_1":"NA"}},{"id":"NOR.9_1","name":"Nord-Trøndelag","bounds":{"min":{"lng":10.13,"lat":63.1782},"max":{"lng":14.3114,"lat":65.3411}},"geojson_properties":{"GID_1":"NOR.9_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Nord-Trøndelag","VARNAME_1":"Nord-Troendelagfylke|NordreTro","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.NT","ISO_1":"NA"}},{"id":"NOR.10_1","name":"Nordland","bounds":{"min":{"lng":11.3818,"lat":64.9418},"max":{"lng":18.1545,"lat":69.325}},"geojson_properties":{"GID_1":"NOR.10_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Nordland","VARNAME_1":"Nordlandfylke","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.NO","ISO_1":"NO-18"}},{"id":"NOR.11_1","name":"Oppland","bounds":{"min":{"lng":7.3466,"lat":60.1218},"max":{"lng":11.1622,"lat":62.3818}},"geojson_properties":{"GID_1":"NOR.11_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Oppland","VARNAME_1":"Opplandfylke|Kristian|Opland|Up","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.OP","ISO_1":"NA"}},{"id":"NOR.12_1","name":"Oslo","bounds":{"min":{"lng":10.5003,"lat":59.8075},"max":{"lng":10.9397,"lat":60.132}},"geojson_properties":{"GID_1":"NOR.12_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Oslo","VARNAME_1":"Oslofylke|Kristiania","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.OS","ISO_1":"NO-03"}},{"id":"NOR.13_1","name":"Rogaland","bounds":{"min":{"lng":4.8447,"lat":58.2704},"max":{"lng":7.1922,"lat":59.8437}},"geojson_properties":{"GID_1":"NOR.13_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Rogaland","VARNAME_1":"Rogalandfylke|Stavanger","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.RO","ISO_1":"NO-11"}},{"id":"NOR.14_1","name":"Sogn og Fjordane","bounds":{"min":{"lng":4.5089,"lat":60.6712},"max":{"lng":8.3295,"lat":62.2104}},"geojson_properties":{"GID_1":"NOR.14_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Sogn og Fjordane","VARNAME_1":"SognogFjordanefyl|NordreBerg","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.SF","ISO_1":"NA"}},{"id":"NOR.15_1","name":"Sør-Trøndelag","bounds":{"min":{"lng":8.2375,"lat":62.2547},"max":{"lng":12.2541,"lat":64.425}},"geojson_properties":{"GID_1":"NOR.15_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Sør-Trøndelag","VARNAME_1":"Soer-Troendelagfylke|SøndreTro","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.ST","ISO_1":"NA"}},{"id":"NOR.16_1","name":"Telemark","bounds":{"min":{"lng":7.095,"lat":58.7637},"max":{"lng":9.8796,"lat":60.1972}},"geojson_properties":{"GID_1":"NOR.16_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Telemark","VARNAME_1":"Telemarkfylke|Bratsberg|Þelamör","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.TE","ISO_1":"NA"}},{"id":"NOR.17_1","name":"Troms","bounds":{"min":{"lng":15.595,"lat":68.3569},"max":{"lng":22.8833,"lat":70.3083}},"geojson_properties":{"GID_1":"NOR.17_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Troms","VARNAME_1":"Tromsfylke|Tromsø|Troms-Fylki","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.TR","ISO_1":"NA"}},{"id":"NOR.18_1","name":"Vest-Agder","bounds":{"min":{"lng":6.3944,"lat":57.959},"max":{"lng":8.2096,"lat":59.1945}},"geojson_properties":{"GID_1":"NOR.18_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Vest-Agder","VARNAME_1":"Vest-Agderfylke|ListerogManda","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.VA","ISO_1":"NA"}},{"id":"NOR.19_1","name":"Vestfold","bounds":{"min":{"lng":9.7505,"lat":58.9368},"max":{"lng":10.5953,"lat":59.6924}},"geojson_properties":{"GID_1":"NOR.19_1","GID_0":"NOR","COUNTRY":"Norway","NAME_1":"Vestfold","VARNAME_1":"Vestfoldfylke|JarlsbergogLarv","NL_NAME_1":"NA","TYPE_1":"Fylke","ENGTYPE_1":"County","CC_1":"NA","HASC_1":"NO.VF","ISO_1":"NA"}}]

=== mrc-ide/grout/region_metadata/gadm41/admin1/region_metadata_MYT_1.json
[{"id":"MYT.1_1","name":"Acoua","bounds":{"min":{"lng":45.0393,"lat":-12.7472},"max":{"lng":45.0964,"lat":-12.7006}},"geojson_properties":{"GID_1":"MYT.1_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Acoua","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Chef-lieucanton","ENGTYPE_1":"Commune","CC_1":"01","HASC_1":"NA","ISO_1":"NA"}},{"id":"MYT.2_1","name":"Bandraboua","bounds":{"min":{"lng":45.0893,"lat":-12.762},"max":{"lng":45.1586,"lat":-12.6721}},"geojson_properties":{"GID_1":"MYT.2_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Bandraboua","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Chef-lieucanton","ENGTYPE_1":"Commune","CC_1":"02","HASC_1":"NA","ISO_1":"-"}},{"id":"MYT.3_1","name":"Bandrele","bounds":{"min":{"lng":45.1409,"lat":-12.996},"max":{"lng":45.2346,"lat":-12.8712}},"geojson_properties":{"GID_1":"MYT.3_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Bandrele","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Chef-lieucanton","ENGTYPE_1":"Commune","CC_1":"03","HASC_1":"NA","ISO_1":"-"}},{"id":"MYT.4_1","name":"Boueni","bounds":{"min":{"lng":45.0704,"lat":-12.9637},"max":{"lng":45.1264,"lat":-12.8971}},"geojson_properties":{"GID_1":"MYT.4_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Boueni","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Chef-lieucanton","ENGTYPE_1":"Commune","CC_1":"04","HASC_1":"NA","ISO_1":"NA"}},{"id":"MYT.5_1","name":"Chiconi","bounds":{"min":{"lng":45.0993,"lat":-12.8413},"max":{"lng":45.1257,"lat":-12.8016}},"geojson_properties":{"GID_1":"MYT.5_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Chiconi","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Chef-lieucanton","ENGTYPE_1":"Commune","CC_1":"05","HASC_1":"NA","ISO_1":"NA"}},{"id":"MYT.6_1","name":"Chirongui","bounds":{"min":{"lng":45.1195,"lat":-12.9656},"max":{"lng":45.1667,"lat":-12.8694}},"geojson_properties":{"GID_1":"MYT.6_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Chirongui","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Chef-lieucanton","ENGTYPE_1":"Commune","CC_1":"06","HASC_1":"NA","ISO_1":"NA"}},{"id":"MYT.7_1","name":"Dembeni","bounds":{"min":{"lng":45.1393,"lat":-12.8868},"max":{"lng":45.2546,"lat":-12.8199}},"geojson_properties":{"GID_1":"MYT.7_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Dembeni","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Chef-lieucanton","ENGTYPE_1":"Commune","CC_1":"07","HASC_1":"NA","ISO_1":"NA"}},{"id":"MYT.8_1","name":"Dzaoudzi","bounds":{"min":{"lng":45.2485,"lat":-12.7929},"max":{"lng":45.2999,"lat":-12.7485}},"geojson_properties":{"GID_1":"MYT.8_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Dzaoudzi","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Préfecturederégion","ENGTYPE_1":"Commune","CC_1":"08","HASC_1":"NA","ISO_1":"NA"}},{"id":"MYT.9_1","name":"Kani-Keli","bounds":{"min":{"lng":45.0793,"lat":-13.0063},"max":{"lng":45.1585,"lat":-12.9439}},"geojson_properties":{"GID_1":"MYT.9_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Kani-Keli","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Chef-lieucanton","ENGTYPE_1":"Commune","CC_1":"09","HASC_1":"NA","ISO_1":"-"}},{"id":"MYT.10_1","name":"Koungou","bounds":{"min":{"lng":45.1451,"lat":-12.7653},"max":{"lng":45.2376,"lat":-12.7176}},"geojson_properties":{"GID_1":"MYT.10_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Koungou","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Chef-lieucanton","ENGTYPE_1":"Commune","CC_1":"10","HASC_1":"NA","ISO_1":"NA"}},{"id":"MYT.11_1","name":"M'tsangamouji","bounds":{"min":{"lng":45.0424,"lat":-12.7793},"max":{"lng":45.126,"lat":-12.7324}},"geojson_properties":{"GID_1":"MYT.11_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"M'tsangamouji","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Chef-lieucanton","ENGTYPE_1":"Commune","CC_1":"13","HASC_1":"NA","ISO_1":"NA"}},{"id":"MYT.12_1","name":"Mamoudzou","bounds":{"min":{"lng":45.1526,"lat":-12.8222},"max":{"lng":45.241,"lat":-12.7539}},"geojson_properties":{"GID_1":"MYT.12_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Mamoudzou","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Sous-préfecture","ENGTYPE_1":"Commune","CC_1":"11","HASC_1":"NA","ISO_1":"-"}},{"id":"MYT.13_1","name":"Mtsamboro","bounds":{"min":{"lng":45.0179,"lat":-12.7156},"max":{"lng":45.1074,"lat":-12.636}},"geojson_properties":{"GID_1":"MYT.13_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Mtsamboro","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Chef-lieucanton","ENGTYPE_1":"Commune","CC_1":"12","HASC_1":"NA","ISO_1":"NA"}},{"id":"MYT.14_1","name":"Ouangani","bounds":{"min":{"lng":45.1216,"lat":-12.874},"max":{"lng":45.1547,"lat":-12.804}},"geojson_properties":{"GID_1":"MYT.14_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Ouangani","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Chef-lieucanton","ENGTYPE_1":"Commune","CC_1":"14","HASC_1":"NA","ISO_1":"-"}},{"id":"MYT.15_1","name":"Pamandzi","bounds":{"min":{"lng":45.2703,"lat":-12.8185},"max":{"lng":45.2971,"lat":-12.7844}},"geojson_properties":{"GID_1":"MYT.15_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Pamandzi","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Chef-lieucanton","ENGTYPE_1":"Commune","CC_1":"15","HASC_1":"NA","ISO_1":"-"}},{"id":"MYT.16_1","name":"Sada","bounds":{"min":{"lng":45.0918,"lat":-12.889},"max":{"lng":45.1384,"lat":-12.8399}},"geojson_properties":{"GID_1":"MYT.16_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Sada","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Chef-lieucanton","ENGTYPE_1":"Commune","CC_1":"16","HASC_1":"NA","ISO_1":"-"}},{"id":"MYT.17_1","name":"Tsingoni","bounds":{"min":{"lng":45.0929,"lat":-12.81},"max":{"lng":45.1731,"lat":-12.7539}},"geojson_properties":{"GID_1":"MYT.17_1","GID_0":"MYT","COUNTRY":"Mayotte","NAME_1":"Tsingoni","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Chef-lieucanton","ENGTYPE_1":"Commune","CC_1":"17","HASC_1":"NA","ISO_1":"NA"}}]

=== mrc-ide/grout/region_metadata/1/region_metadata_region_metadata_MRT_1.json
[{"id":"MRT.1_1","name":"Adrar","bounds":{"min":{"lng":-14.3012,"lat":18.5571},"max":{"lng":-6.3548,"lat":24.3067}},"geojson_properties":{"GID_1":"MRT.1_1","GID_0":"MRT","COUNTRY":"Mauritania","NAME_1":"Adrar","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Wilayat|Région","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MR.AD","ISO_1":"MR-07"}},{"id":"MRT.2_1","name":"Assaba","bounds":{"min":{"lng":-12.839,"lat":15.1036},"max":{"lng":-10.5846,"lat":18.311}},"geojson_properties":{"GID_1":"MRT.2_1","GID_0":"MRT","COUNTRY":"Mauritania","NAME_1":"Assaba","VARNAME_1":"Açaba|el-`Açâba","NL_NAME_1":"NA","TYPE_1":"Wilayat|Région","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MR.AS","ISO_1":"MR-03"}},{"id":"MRT.3_1","name":"Brakna","bounds":{"min":{"lng":-14.9546,"lat":16.1064},"max":{"lng":-12.3102,"lat":18.5571}},"geojson_properties":{"GID_1":"MRT.3_1","GID_0":"MRT","COUNTRY":"Mauritania","NAME_1":"Brakna","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Wilayat|Région","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MR.BR","ISO_1":"MR-05"}},{"id":"MRT.4_1","name":"Dakhlet Nouadhibou","bounds":{"min":{"lng":-17.0665,"lat":19.4068},"max":{"lng":-14.1731,"lat":21.3436}},"geojson_properties":{"GID_1":"MRT.4_1","GID_0":"MRT","COUNTRY":"Mauritania","NAME_1":"Dakhlet Nouadhibou","VARNAME_1":"DakhletNouâdhibou|BaieduLévri","NL_NAME_1":"NA","TYPE_1":"Wilayat|Région","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MR.DN","ISO_1":"MR-08"}},{"id":"MRT.5_1","name":"Gorgol","bounds":{"min":{"lng":-13.7199,"lat":15.1304},"max":{"lng":-12.0049,"lat":16.8584}},"geojson_properties":{"GID_1":"MRT.5_1","GID_0":"MRT","COUNTRY":"Mauritania","NAME_1":"Gorgol","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Wilayat|Région","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MR.GO","ISO_1":"MR-04"}},{"id":"MRT.6_1","name":"Guidimaka","bounds":{"min":{"lng":-12.7468,"lat":14.7156},"max":{"lng":-11.5003,"lat":16.0562}},"geojson_properties":{"GID_1":"MRT.6_1","GID_0":"MRT","COUNTRY":"Mauritania","NAME_1":"Guidimaka","VARNAME_1":"Guidimagha|Guidimakha","NL_NAME_1":"NA","TYPE_1":"Wilayat|Région","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MR.GD","ISO_1":"NA"}},{"id":"MRT.7_1","name":"Hodh ech Chargui","bounds":{"min":{"lng":-9.1497,"lat":15.4941},"max":{"lng":-5.3271,"lat":23.1581}},"geojson_properties":{"GID_1":"MRT.7_1","GID_0":"MRT","COUNTRY":"Mauritania","NAME_1":"Hodh ech Chargui","VARNAME_1":"EasternHodh|HodhCharghi|HodhO","NL_NAME_1":"NA","TYPE_1":"Wilayat|Région","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MR.HC","ISO_1":"MR-01"}},{"id":"MRT.8_1","name":"Hodh el Gharbi","bounds":{"min":{"lng":-11.0958,"lat":15.3566},"max":{"lng":-8.2892,"lat":17.7229}},"geojson_properties":{"GID_1":"MRT.8_1","GID_0":"MRT","COUNTRY":"Mauritania","NAME_1":"Hodh el Gharbi","VARNAME_1":"HodhOccidental|WesternHodh","NL_NAME_1":"NA","TYPE_1":"Wilayat|Région","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MR.HG","ISO_1":"MR-02"}},{"id":"MRT.9_1","name":"Inchiri","bounds":{"min":{"lng":-16.5446,"lat":18.9959},"max":{"lng":-14.1544,"lat":21.1508}},"geojson_properties":{"GID_1":"MRT.9_1","GID_0":"MRT","COUNTRY":"Mauritania","NAME_1":"Inchiri","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Wilayat|Région","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MR.IN","ISO_1":"MR-12"}},{"id":"MRT.10_1","name":"Nouakchott","bounds":{"min":{"lng":-16.0504,"lat":17.8865},"max":{"lng":-15.78,"lat":18.3931}},"geojson_properties":{"GID_1":"MRT.10_1","GID_0":"MRT","COUNTRY":"Mauritania","NAME_1":"Nouakchott","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"District","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"MR.NO","ISO_1":"NA"}},{"id":"MRT.11_1","name":"Tagant","bounds":{"min":{"lng":-12.669,"lat":17.0804},"max":{"lng":-7.9877,"lat":19.7255}},"geojson_properties":{"GID_1":"MRT.11_1","GID_0":"MRT","COUNTRY":"Mauritania","NAME_1":"Tagant","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Wilayat|Région","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MR.TG","ISO_1":"MR-09"}},{"id":"MRT.12_1","name":"Tiris Zemmour","bounds":{"min":{"lng":-13.1457,"lat":21.3517},"max":{"lng":-4.83,"lat":27.2981}},"geojson_properties":{"GID_1":"MRT.12_1","GID_0":"MRT","COUNTRY":"Mauritania","NAME_1":"Tiris Zemmour","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Wilayat|Région","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MR.TZ","ISO_1":"MR-11"}},{"id":"MRT.13_1","name":"Trarza","bounds":{"min":{"lng":-16.5207,"lat":16.0617},"max":{"lng":-12.669,"lat":19.0006}},"geojson_properties":{"GID_1":"MRT.13_1","GID_0":"MRT","COUNTRY":"Mauritania","NAME_1":"Trarza","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Wilayat|Région","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"MR.TR","ISO_1":"MR-06"}}]
