=== mrc-ide/grout/schema/RegionMetadata.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "bounds": {
        "type": "object",
        "properties": {
          "min": { "$ref": "#/$defs/lat-lng" },
          "max": { "$ref": "#/$defs/lat-lng" }
        },
        "additionalProperties": false,
        "required": [
          "min",
          "max"
        ]
      },
      "geojson_properties": { "type": "object" }
    },
    "additionalProperties": false,
    "required": [
      "id",
      "name",
      "bounds",
      "geojson_properties"
    ]
  },
  "$defs": {
    "lat-lng": {
      "type": "object",
      "properties": {
        "lat": { "type": "number" },
        "lng": { "type": "number" }
      },
      "additionalProperties": false,
      "required": ["lat", "lng"]
    }
  }
}

=== mrc-ide/grout/data/region_metadata/gadm41/admin1/region_metadata_LKA_1.json
[{"id":"LKA.1_1","name":"Ampara","bounds":{"min":{"lng":80.9779,"lat":6.5126},"max":{"lng":81.8788,"lat":7.7392}},"geojson_properties":{"GID_1":"LKA.1_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Ampara","VARNAME_1":"Amparai","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.AP","ISO_1":"NA"}},{"id":"LKA.2_1","name":"Anuradhapura","bounds":{"min":{"lng":79.9519,"lat":7.8151},"max":{"lng":80.9908,"lat":8.9206}},"geojson_properties":{"GID_1":"LKA.2_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Anuradhapura","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.AD","ISO_1":"NA"}},{"id":"LKA.3_1","name":"Badulla","bounds":{"min":{"lng":80.7771,"lat":6.5422},"max":{"lng":81.2716,"lat":7.625}},"geojson_properties":{"GID_1":"LKA.3_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Badulla","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.BD","ISO_1":"NA"}},{"id":"LKA.4_1","name":"Batticaloa","bounds":{"min":{"lng":81.2249,"lat":7.3988},"max":{"lng":81.8166,"lat":8.2681}},"geojson_properties":{"GID_1":"LKA.4_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Batticaloa","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.BC","ISO_1":"NA"}},{"id":"LKA.5_1","name":"Colombo","bounds":{"min":{"lng":79.8399,"lat":6.7141},"max":{"lng":80.2234,"lat":6.9794}},"geojson_properties":{"GID_1":"LKA.5_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Colombo","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.CO","ISO_1":"NA"}},{"id":"LKA.6_1","name":"Galle","bounds":{"min":{"lng":79.989,"lat":5.9651},"max":{"lng":80.4957,"lat":6.4396}},"geojson_properties":{"GID_1":"LKA.6_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Galle","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.GL","ISO_1":"NA"}},{"id":"LKA.7_1","name":"Gampaha","bounds":{"min":{"lng":79.8171,"lat":6.9073},"max":{"lng":80.2084,"lat":7.3306}},"geojson_properties":{"GID_1":"LKA.7_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Gampaha","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.GQ","ISO_1":"NA"}},{"id":"LKA.8_1","name":"Hambantota","bounds":{"min":{"lng":80.6083,"lat":5.9718},"max":{"lng":81.706,"lat":6.5788}},"geojson_properties":{"GID_1":"LKA.8_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Hambantota","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.HB","ISO_1":"NA"}},{"id":"LKA.9_1","name":"Jaffna","bounds":{"min":{"lng":79.5221,"lat":9.384},"max":{"lng":80.6196,"lat":9.836}},"geojson_properties":{"GID_1":"LKA.9_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Jaffna","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.JA","ISO_1":"NA"}},{"id":"LKA.10_1","name":"Kalutara","bounds":{"min":{"lng":79.8865,"lat":6.3249},"max":{"lng":80.3819,"lat":6.8249}},"geojson_properties":{"GID_1":"LKA.10_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Kalutara","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.KT","ISO_1":"NA"}},{"id":"LKA.11_1","name":"Kandy","bounds":{"min":{"lng":80.422,"lat":6.9388},"max":{"lng":81.0165,"lat":7.4899}},"geojson_properties":{"GID_1":"LKA.11_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Kandy","VARNAME_1":"MahaNuwara","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.KY","ISO_1":"NA"}},{"id":"LKA.12_1","name":"Kegalle","bounds":{"min":{"lng":80.1453,"lat":6.83},"max":{"lng":80.5481,"lat":7.3967}},"geojson_properties":{"GID_1":"LKA.12_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Kegalle","VARNAME_1":"Kegalla","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.KE","ISO_1":"NA"}},{"id":"LKA.13_1","name":"Kilinochchi","bounds":{"min":{"lng":79.8843,"lat":9.2086},"max":{"lng":80.6155,"lat":9.6913}},"geojson_properties":{"GID_1":"LKA.13_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Kilinochchi","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.KL","ISO_1":"NA"}},{"id":"LKA.14_1","name":"Kurunegala","bounds":{"min":{"lng":79.9004,"lat":7.2562},"max":{"lng":80.5759,"lat":8.1964}},"geojson_properties":{"GID_1":"LKA.14_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Kurunegala","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.KG","ISO_1":"NA"}},{"id":"LKA.15_1","name":"Mannar","bounds":{"min":{"lng":79.6396,"lat":8.5219},"max":{"lng":80.4025,"lat":9.2373}},"geojson_properties":{"GID_1":"LKA.15_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Mannar","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.MB","ISO_1":"NA"}},{"id":"LKA.16_1","name":"Matale","bounds":{"min":{"lng":80.4944,"lat":7.3841},"max":{"lng":80.9947,"lat":8.0124}},"geojson_properties":{"GID_1":"LKA.16_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Matale","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.MT","ISO_1":"NA"}},{"id":"LKA.17_1","name":"Matara","bounds":{"min":{"lng":80.3775,"lat":5.9185},"max":{"lng":80.7241,"lat":6.3975}},"geojson_properties":{"GID_1":"LKA.17_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Matara","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.MH","ISO_1":"NA"}},{"id":"LKA.18_1","name":"Moneragala","bounds":{"min":{"lng":80.8278,"lat":6.2958},"max":{"lng":81.6372,"lat":7.458}},"geojson_properties":{"GID_1":"LKA.18_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Moneragala","VARNAME_1":"Monaragala","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.MJ","ISO_1":"NA"}},{"id":"LKA.19_1","name":"Mullaitivu","bounds":{"min":{"lng":80.175,"lat":8.9369},"max":{"lng":80.964,"lat":9.4579}},"geojson_properties":{"GID_1":"LKA.19_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Mullaitivu","VARNAME_1":"Mulativu","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.MP","ISO_1":"NA"}},{"id":"LKA.20_1","name":"Nuwara Eliya","bounds":{"min":{"lng":80.4324,"lat":6.7514},"max":{"lng":80.9663,"lat":7.2739}},"geojson_properties":{"GID_1":"LKA.20_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Nuwara Eliya","VARNAME_1":"NuvaraEliya","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.NW","ISO_1":"NA"}},{"id":"LKA.21_1","name":"Polonnaruwa","bounds":{"min":{"lng":80.7494,"lat":7.647},"max":{"lng":81.34,"lat":8.3452}},"geojson_properties":{"GID_1":"LKA.21_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Polonnaruwa","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.PR","ISO_1":"NA"}},{"id":"LKA.22_1","name":"Puttalam","bounds":{"min":{"lng":79.6929,"lat":7.2669},"max":{"lng":80.1533,"lat":8.5655}},"geojson_properties":{"GID_1":"LKA.22_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Puttalam","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.PX","ISO_1":"NA"}},{"id":"LKA.23_1","name":"Ratnapura","bounds":{"min":{"lng":80.177,"lat":6.2279},"max":{"lng":80.9527,"lat":6.9311}},"geojson_properties":{"GID_1":"LKA.23_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Ratnapura","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.RN","ISO_1":"NA"}},{"id":"LKA.24_1","name":"Trincomalee","bounds":{"min":{"lng":80.753,"lat":8.1488},"max":{"lng":81.404,"lat":8.9909}},"geojson_properties":{"GID_1":"LKA.24_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Trincomalee","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.TC","ISO_1":"NA"}},{"id":"LKA.25_1","name":"Vavuniya","bounds":{"min":{"lng":80.17,"lat":8.546},"max":{"lng":80.787,"lat":9.1263}},"geojson_properties":{"GID_1":"LKA.25_1","GID_0":"LKA","COUNTRY":"Sri Lanka","NAME_1":"Vavuniya","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Distrikkaya","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LK.VA","ISO_1":"NA"}}]

=== mrc-ide/grout/region_metadata/1/region_metadata_region_metadata_PAN_1.json
[{"id":"PAN.1_1","name":"Bocas del Toro","bounds":{"min":{"lng":-82.9342,"lat":8.8279},"max":{"lng":-81.9157,"lat":9.6165}},"geojson_properties":{"GID_1":"PAN.1_1","GID_0":"PAN","COUNTRY":"Panama","NAME_1":"Bocas del Toro","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Provincia","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"PA.BC","ISO_1":"PA-1"}},{"id":"PAN.2_1","name":"Chiriquí","bounds":{"min":{"lng":-83.0519,"lat":7.8593},"max":{"lng":-81.5074,"lat":8.9195}},"geojson_properties":{"GID_1":"PAN.2_1","GID_0":"PAN","COUNTRY":"Panama","NAME_1":"Chiriquí","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Provincia","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"PA.CH","ISO_1":"NA"}},{"id":"PAN.3_1","name":"Coclé","bounds":{"min":{"lng":-80.8229,"lat":8.0871},"max":{"lng":-80.0527,"lat":9.064}},"geojson_properties":{"GID_1":"PAN.3_1","GID_0":"PAN","COUNTRY":"Panama","NAME_1":"Coclé","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Provincia","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"PA.CC","ISO_1":"NA"}},{"id":"PAN.4_1","name":"Colón","bounds":{"min":{"lng":-80.8766,"lat":8.6327},"max":{"lng":-79.0803,"lat":9.6468}},"geojson_properties":{"GID_1":"PAN.4_1","GID_0":"PAN","COUNTRY":"Panama","NAME_1":"Colón","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Provincia","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"PA.CL","ISO_1":"NA"}},{"id":"PAN.5_1","name":"Darién","bounds":{"min":{"lng":-78.5125,"lat":7.2184},"max":{"lng":-77.1293,"lat":9.0927}},"geojson_properties":{"GID_1":"PAN.5_1","GID_0":"PAN","COUNTRY":"Panama","NAME_1":"Darién","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Provincia","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"PA.DR","ISO_1":"NA"}},{"id":"PAN.6_1","name":"Emberá","bounds":{"min":{"lng":-78.3374,"lat":7.5815},"max":{"lng":-77.2392,"lat":8.7776}},"geojson_properties":{"GID_1":"PAN.6_1","GID_0":"PAN","COUNTRY":"Panama","NAME_1":"Emberá","VARNAME_1":"Emberá-Wounaan","NL_NAME_1":"NA","TYPE_1":"ComarcaIndígena","ENGTYPE_1":"IndigenousTerritory","CC_1":"NA","HASC_1":"PA.EM","ISO_1":"NA"}},{"id":"PAN.7_1","name":"Herrera","bounds":{"min":{"lng":-80.9633,"lat":7.5101},"max":{"lng":-80.3662,"lat":8.1317}},"geojson_properties":{"GID_1":"PAN.7_1","GID_0":"PAN","COUNTRY":"Panama","NAME_1":"Herrera","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Provincia","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"PA.HE","ISO_1":"PA-6"}},{"id":"PAN.8_1","name":"Kuna Yala","bounds":{"min":{"lng":-79.2824,"lat":8.5012},"max":{"lng":-77.3574,"lat":9.6004}},"geojson_properties":{"GID_1":"PAN.8_1","GID_0":"PAN","COUNTRY":"Panama","NAME_1":"Kuna Yala","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"ComarcaIndígena","ENGTYPE_1":"IndigenousTerritory","CC_1":"NA","HASC_1":"PA.SB","ISO_1":"NA"}},{"id":"PAN.9_1","name":"Los Santos","bounds":{"min":{"lng":-80.7383,"lat":7.2274},"max":{"lng":-79.9912,"lat":8.004}},"geojson_properties":{"GID_1":"PAN.9_1","GID_0":"PAN","COUNTRY":"Panama","NAME_1":"Los Santos","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Provincia","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"PA.LS","ISO_1":"PA-7"}},{"id":"PAN.10_1","name":"Ngöbe Buglé","bounds":{"min":{"lng":-82.4455,"lat":8.1459},"max":{"lng":-81.1327,"lat":9.1865}},"geojson_properties":{"GID_1":"PAN.10_1","GID_0":"PAN","COUNTRY":"Panama","NAME_1":"Ngöbe Buglé","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"ComarcaIndígena","ENGTYPE_1":"IndigenousTerritory","CC_1":"NA","HASC_1":"PA.NB","ISO_1":"NA"}},{"id":"PAN.12_1","name":"Panamá","bounds":{"min":{"lng":-79.6949,"lat":7.9999},"max":{"lng":-78.05,"lat":9.5233}},"geojson_properties":{"GID_1":"PAN.12_1","GID_0":"PAN","COUNTRY":"Panama","NAME_1":"Panamá","VARNAME_1":"Panam ","NL_NAME_1":"NA","TYPE_1":"Provincia","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"PA.PN","ISO_1":"NA"}},{"id":"PAN.11_1","name":"Panamá Oeste","bounds":{"min":{"lng":-80.1704,"lat":8.4013},"max":{"lng":-79.509,"lat":9.1903}},"geojson_properties":{"GID_1":"PAN.11_1","GID_0":"PAN","COUNTRY":"Panama","NAME_1":"Panamá Oeste","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Provincia","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"PA.PO","ISO_1":"NA"}},{"id":"PAN.13_1","name":"Veraguas","bounds":{"min":{"lng":-82.264,"lat":7.2024},"max":{"lng":-80.6147,"lat":9.0001}},"geojson_properties":{"GID_1":"PAN.13_1","GID_0":"PAN","COUNTRY":"Panama","NAME_1":"Veraguas","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Provincia","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"PA.VR","ISO_1":"PA-9"}}]

=== mrc-ide/grout/data/region_metadata/gadm41/admin1/region_metadata_GRL_1.json
[{"id":"GRL.1_1","name":"Kujalleq","bounds":{"min":{"lng":-48.2578,"lat":59.7447},"max":{"lng":-42.0615,"lat":62.7958}},"geojson_properties":{"GID_1":"GRL.1_1","GID_0":"GRL","COUNTRY":"Greenland","NAME_1":"Kujalleq","VARNAME_1":"KommuneKujalleq|Kitaa|WestGree","NL_NAME_1":"NA","TYPE_1":"Kommuner","ENGTYPE_1":"Commune","CC_1":"NA","HASC_1":"GL.KU","ISO_1":"NA"}},{"id":"GRL.2_1","name":"Northeast Greenland National Par","bounds":{"min":{"lng":-61.9792,"lat":70.828},"max":{"lng":-0.013,"lat":83.6583}},"geojson_properties":{"GID_1":"GRL.2_1","GID_0":"GRL","COUNTRY":"Greenland","NAME_1":"Northeast Greenland National Par","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"NationalPark","ENGTYPE_1":"NationalPark","CC_1":"NA","HASC_1":"GL.UO","ISO_1":"NA"}},{"id":"GRL.3_1","name":"Qaasuitsup","bounds":{"min":{"lng":-73.2432,"lat":67.2083},"max":{"lng":-44.0968,"lat":81.2042}},"geojson_properties":{"GID_1":"GRL.3_1","GID_0":"GRL","COUNTRY":"Greenland","NAME_1":"Qaasuitsup","VARNAME_1":"QaasuitsupKommunia|Avannaa|Kita","NL_NAME_1":"NA","TYPE_1":"Kommuner","ENGTYPE_1":"Commune","CC_1":"NA","HASC_1":"GL.QS","ISO_1":"NA"}},{"id":"GRL.4_1","name":"Qeqqata","bounds":{"min":{"lng":-53.9661,"lat":64.0047},"max":{"lng":-43.867,"lat":67.633}},"geojson_properties":{"GID_1":"GRL.4_1","GID_0":"GRL","COUNTRY":"Greenland","NAME_1":"Qeqqata","VARNAME_1":"QeqqataKommunia|Kitaa|WestGree","NL_NAME_1":"NA","TYPE_1":"Kommuner","ENGTYPE_1":"Commune","CC_1":"NA","HASC_1":"GL.QT","ISO_1":"NA"}},{"id":"GRL.5_1","name":"Sermersooq","bounds":{"min":{"lng":-51.9036,"lat":60.7958},"max":{"lng":-21.388,"lat":72.0208}},"geojson_properties":{"GID_1":"GRL.5_1","GID_0":"GRL","COUNTRY":"Greenland","NAME_1":"Sermersooq","VARNAME_1":"KommuneqarfikSermersooq|Tunu|Ea","NL_NAME_1":"NA","TYPE_1":"Kommuner","ENGTYPE_1":"Commune","CC_1":"NA","HASC_1":"GL.SE","ISO_1":"NA"}}]

=== mrc-ide/grout/data/region_metadata/gadm41/admin1/region_metadata_LSO_1.json
[{"id":"LSO.1_1","name":"Berea","bounds":{"min":{"lng":27.5117,"lat":-29.3967},"max":{"lng":28.2944,"lat":-28.9465}},"geojson_properties":{"GID_1":"LSO.1_1","GID_0":"LSO","COUNTRY":"Lesotho","NAME_1":"Berea","VARNAME_1":"Teyateyaneng","NL_NAME_1":"NA","TYPE_1":"District","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LS.BE","ISO_1":"LS-D"}},{"id":"LSO.2_1","name":"Butha-Buthe","bounds":{"min":{"lng":28.224,"lat":-29.0863},"max":{"lng":28.8188,"lat":-28.5708}},"geojson_properties":{"GID_1":"LSO.2_1","GID_0":"LSO","COUNTRY":"Lesotho","NAME_1":"Butha-Buthe","VARNAME_1":"ButhaButhe","NL_NAME_1":"NA","TYPE_1":"District","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LS.BB","ISO_1":"NA"}},{"id":"LSO.3_1","name":"Leribe","bounds":{"min":{"lng":27.6414,"lat":-29.3703},"max":{"lng":28.7936,"lat":-28.6937}},"geojson_properties":{"GID_1":"LSO.3_1","GID_0":"LSO","COUNTRY":"Lesotho","NAME_1":"Leribe","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"District","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LS.LE","ISO_1":"LS-C"}},{"id":"LSO.4_1","name":"Mafeteng","bounds":{"min":{"lng":27.0116,"lat":-30.0569},"max":{"lng":28.3147,"lat":-29.5263}},"geojson_properties":{"GID_1":"LSO.4_1","GID_0":"LSO","COUNTRY":"Lesotho","NAME_1":"Mafeteng","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"District","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LS.MF","ISO_1":"LS-E"}},{"id":"LSO.5_1","name":"Maseru","bounds":{"min":{"lng":27.3002,"lat":-29.9257},"max":{"lng":28.2109,"lat":-29.2822}},"geojson_properties":{"GID_1":"LSO.5_1","GID_0":"LSO","COUNTRY":"Lesotho","NAME_1":"Maseru","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"District","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LS.MS","ISO_1":"LS-A"}},{"id":"LSO.6_1","name":"Mohale's Hoek","bounds":{"min":{"lng":27.1765,"lat":-30.4177},"max":{"lng":28.5951,"lat":-29.7873}},"geojson_properties":{"GID_1":"LSO.6_1","GID_0":"LSO","COUNTRY":"Lesotho","NAME_1":"Mohale's Hoek","VARNAME_1":"MohalesHoek","NL_NAME_1":"NA","TYPE_1":"District","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LS.MH","ISO_1":"LS-F"}},{"id":"LSO.7_1","name":"Mokhotlong","bounds":{"min":{"lng":28.5573,"lat":-29.5811},"max":{"lng":29.4557,"lat":-28.756}},"geojson_properties":{"GID_1":"LSO.7_1","GID_0":"LSO","COUNTRY":"Lesotho","NAME_1":"Mokhotlong","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"District","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LS.MK","ISO_1":"LS-J"}},{"id":"LSO.8_1","name":"Qacha's Nek","bounds":{"min":{"lng":28.2253,"lat":-30.1697},"max":{"lng":29.1694,"lat":-29.7094}},"geojson_properties":{"GID_1":"LSO.8_1","GID_0":"LSO","COUNTRY":"Lesotho","NAME_1":"Qacha's Nek","VARNAME_1":"Quacha'sNek|QuachasNek","NL_NAME_1":"NA","TYPE_1":"District","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LS.QN","ISO_1":"LS-H"}},{"id":"LSO.9_1","name":"Quthing","bounds":{"min":{"lng":27.5619,"lat":-30.6756},"max":{"lng":28.373,"lat":-30.0224}},"geojson_properties":{"GID_1":"LSO.9_1","GID_0":"LSO","COUNTRY":"Lesotho","NAME_1":"Quthing","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"District","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LS.QT","ISO_1":"LS-G"}},{"id":"LSO.10_1","name":"Thaba-Tseka","bounds":{"min":{"lng":28.0932,"lat":-29.8976},"max":{"lng":29.3243,"lat":-29.1198}},"geojson_properties":{"GID_1":"LSO.10_1","GID_0":"LSO","COUNTRY":"Lesotho","NAME_1":"Thaba-Tseka","VARNAME_1":"ThabaTseka","NL_NAME_1":"NA","TYPE_1":"District","ENGTYPE_1":"District","CC_1":"NA","HASC_1":"LS.TT","ISO_1":"LS-K"}}]

=== mrc-ide/grout/data/region_metadata/gadm41/admin1/region_metadata_AZE_1.json
[{"id":"AZE.1_1","name":"Absheron","bounds":{"min":{"lng":48.7634,"lat":39.665},"max":{"lng":50.6078,"lat":40.9809}},"geojson_properties":{"GID_1":"AZE.1_1","GID_0":"AZE","COUNTRY":"Azerbaijan","NAME_1":"Absheron","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"İqtisadiRayonu","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"NA","ISO_1":"NA"}},{"id":"AZE.2_1","name":"Aran","bounds":{"min":{"lng":46.7298,"lat":39.1282},"max":{"lng":49.4393,"lat":40.9687}},"geojson_properties":{"GID_1":"AZE.2_1","GID_0":"AZE","COUNTRY":"Azerbaijan","NAME_1":"Aran","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"İqtisadiRayonu","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"NA","ISO_1":"NA"}},{"id":"AZE.3_1","name":"Daglig-Shirvan","bounds":{"min":{"lng":47.7325,"lat":40.2648},"max":{"lng":49.2631,"lat":41.0631}},"geojson_properties":{"GID_1":"AZE.3_1","GID_0":"AZE","COUNTRY":"Azerbaijan","NAME_1":"Daglig-Shirvan","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"İqtisadiRayonu","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"NA","ISO_1":"NA"}},{"id":"AZE.4_1","name":"Ganja-Qazakh","bounds":{"min":{"lng":45.0026,"lat":40.2564},"max":{"lng":46.9636,"lat":41.4681}},"geojson_properties":{"GID_1":"AZE.4_1","GID_0":"AZE","COUNTRY":"Azerbaijan","NAME_1":"Ganja-Qazakh","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"İqtisadiRayonu","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"NA","ISO_1":"NA"}},{"id":"AZE.5_1","name":"Kalbajar-Lachin","bounds":{"min":{"lng":45.5786,"lat":38.8727},"max":{"lng":46.8722,"lat":40.3145}},"geojson_properties":{"GID_1":"AZE.5_1","GID_0":"AZE","COUNTRY":"Azerbaijan","NAME_1":"Kalbajar-Lachin","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"İqtisadiRayonu","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"NA","ISO_1":"NA"}},{"id":"AZE.6_1","name":"Lankaran","bounds":{"min":{"lng":48.0091,"lat":38.3972},"max":{"lng":49.2378,"lat":39.4215}},"geojson_properties":{"GID_1":"AZE.6_1","GID_0":"AZE","COUNTRY":"Azerbaijan","NAME_1":"Lankaran","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"İqtisadiRayonu","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"NA","ISO_1":"AZ-LA"}},{"id":"AZE.7_1","name":"Nakhchivan","bounds":{"min":{"lng":44.7726,"lat":38.8202},"max":{"lng":46.1509,"lat":39.7855}},"geojson_properties":{"GID_1":"AZE.7_1","GID_0":"AZE","COUNTRY":"Azerbaijan","NAME_1":"Nakhchivan","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"İqtisadiRayonu","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"NA","ISO_1":"NA"}},{"id":"AZE.8_1","name":"Quba-Khachmaz","bounds":{"min":{"lng":47.802,"lat":40.8551},"max":{"lng":49.3671,"lat":41.885}},"geojson_properties":{"GID_1":"AZE.8_1","GID_0":"AZE","COUNTRY":"Azerbaijan","NAME_1":"Quba-Khachmaz","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"İqtisadiRayonu","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"NA","ISO_1":"NA"}},{"id":"AZE.9_1","name":"Shaki-Zaqatala","bounds":{"min":{"lng":46.2478,"lat":40.6395},"max":{"lng":48.0311,"lat":41.9075}},"geojson_properties":{"GID_1":"AZE.9_1","GID_0":"AZE","COUNTRY":"Azerbaijan","NAME_1":"Shaki-Zaqatala","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"İqtisadiRayonu","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"NA","ISO_1":"NA"}},{"id":"AZE.10_1","name":"Yukhari-Karabakh","bounds":{"min":{"lng":46.4341,"lat":39.1325},"max":{"lng":47.6405,"lat":40.48}},"geojson_properties":{"GID_1":"AZE.10_1","GID_0":"AZE","COUNTRY":"Azerbaijan","NAME_1":"Yukhari-Karabakh","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"İqtisadiRayonu","ENGTYPE_1":"Region","CC_1":"NA","HASC_1":"NA","ISO_1":"NA"}}]

=== mrc-ide/grout/region_metadata/gadm41/1/region_metadata_NLD_1.json
[{"id":"NLD.1_1","name":"Drenthe","bounds":{"min":{"lng":6.1263,"lat":52.6132},"max":{"lng":7.0927,"lat":53.2039}},"geojson_properties":{"GID_1":"NLD.1_1","GID_0":"NLD","COUNTRY":"Netherlands","NAME_1":"Drenthe","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Provincie","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"NL.DR","ISO_1":"NL-DR"}},{"id":"NLD.2_1","name":"Flevoland","bounds":{"min":{"lng":5.1267,"lat":52.2533},"max":{"lng":5.9913,"lat":52.8436}},"geojson_properties":{"GID_1":"NLD.2_1","GID_0":"NLD","COUNTRY":"Netherlands","NAME_1":"Flevoland","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Provincie","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"NL.FL","ISO_1":"NL-FL"}},{"id":"NLD.3_1","name":"Fryslân","bounds":{"min":{"lng":4.8497,"lat":52.801},"max":{"lng":6.436,"lat":53.5096}},"geojson_properties":{"GID_1":"NLD.3_1","GID_0":"NLD","COUNTRY":"Netherlands","NAME_1":"Fryslân","VARNAME_1":"Friesland","NL_NAME_1":"NA","TYPE_1":"Provincie","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"NL.FR","ISO_1":"NL-FR"}},{"id":"NLD.4_1","name":"Gelderland","bounds":{"min":{"lng":4.9979,"lat":51.7343},"max":{"lng":6.8328,"lat":52.5219}},"geojson_properties":{"GID_1":"NLD.4_1","GID_0":"NLD","COUNTRY":"Netherlands","NAME_1":"Gelderland","VARNAME_1":"Geldern|Gheldria|Guelders|Gueldr","NL_NAME_1":"NA","TYPE_1":"Provincie","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"NL.GE","ISO_1":"NL-GE"}},{"id":"NLD.5_1","name":"Groningen","bounds":{"min":{"lng":6.1739,"lat":52.839},"max":{"lng":7.227,"lat":53.5546}},"geojson_properties":{"GID_1":"NLD.5_1","GID_0":"NLD","COUNTRY":"Netherlands","NAME_1":"Groningen","VARNAME_1":"Groninga|Groningue","NL_NAME_1":"NA","TYPE_1":"Provincie","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"NL.GR","ISO_1":"NL-GR"}},{"id":"NLD.6_1","name":"IJsselmeer","bounds":{"min":{"lng":4.9616,"lat":52.2452},"max":{"lng":6.0296,"lat":53.0907}},"geojson_properties":{"GID_1":"NLD.6_1","GID_0":"NLD","COUNTRY":"Netherlands","NAME_1":"IJsselmeer","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Waterbody","ENGTYPE_1":"Waterbody","CC_1":"NA","HASC_1":"NA","ISO_1":"NA"}},{"id":"NLD.7_1","name":"Limburg","bounds":{"min":{"lng":5.5706,"lat":50.7235},"max":{"lng":6.2264,"lat":51.7795}},"geojson_properties":{"GID_1":"NLD.7_1","GID_0":"NLD","COUNTRY":"Netherlands","NAME_1":"Limburg","VARNAME_1":"Limbourg|Limburgo","NL_NAME_1":"NA","TYPE_1":"Provincie","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"NL.LI","ISO_1":"NL-LI"}},{"id":"NLD.8_1","name":"Noord-Brabant","bounds":{"min":{"lng":4.1917,"lat":51.2215},"max":{"lng":6.0564,"lat":51.8314}},"geojson_properties":{"GID_1":"NLD.8_1","GID_0":"NLD","COUNTRY":"Netherlands","NAME_1":"Noord-Brabant","VARNAME_1":"BrabantedelNorte|BrabantedoN","NL_NAME_1":"NA","TYPE_1":"Provincie","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"NL.NB","ISO_1":"NL-NB"}},{"id":"NLD.9_1","name":"Noord-Holland","bounds":{"min":{"lng":4.4942,"lat":52.1656},"max":{"lng":5.3216,"lat":53.1832}},"geojson_properties":{"GID_1":"NLD.9_1","GID_0":"NLD","COUNTRY":"Netherlands","NAME_1":"Noord-Holland","VARNAME_1":"HolandadoNorte|Hollande-septen","NL_NAME_1":"NA","TYPE_1":"Provincie","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"NL.NH","ISO_1":"NL-NH"}},{"id":"NLD.10_1","name":"Overijssel","bounds":{"min":{"lng":5.7844,"lat":52.1182},"max":{"lng":7.0722,"lat":52.8537}},"geojson_properties":{"GID_1":"NLD.10_1","GID_0":"NLD","COUNTRY":"Netherlands","NAME_1":"Overijssel","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Provincie","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"NL.OV","ISO_1":"NL-OV"}},{"id":"NLD.11_1","name":"Utrecht","bounds":{"min":{"lng":4.7944,"lat":51.8586},"max":{"lng":5.6337,"lat":52.3037}},"geojson_properties":{"GID_1":"NLD.11_1","GID_0":"NLD","COUNTRY":"Netherlands","NAME_1":"Utrecht","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Provincie","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"NL.UT","ISO_1":"NL-UT"}},{"id":"NLD.12_1","name":"Zeeland","bounds":{"min":{"lng":3.3608,"lat":51.1989},"max":{"lng":4.2781,"lat":51.7579}},"geojson_properties":{"GID_1":"NLD.12_1","GID_0":"NLD","COUNTRY":"Netherlands","NAME_1":"Zeeland","VARNAME_1":"Zelanda|Zélande|Zelândia","NL_NAME_1":"NA","TYPE_1":"Provincie","ENGTYPE_1":"Province","CC_1":"NA","HASC_1":"NL.ZE","ISO_1":"NL-ZE"}},{"id":"NLD.13_1","name":"Zeeuwse meren","bounds":{"min":{"lng":3.6273,"lat":51.4317},"max":{"lng":4.4114,"lat":51.7737}},"geojson_properties":{"GID_1":"NLD.13_1","GID_0":"NLD","COUNTRY":"Netherlands","NAME_1":"Zeeuwse meren","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"Waterbody","ENGTYPE_1":"Waterbody","CC_1":"NA","HASC_1":"NA","ISO_1":"NA"}},{"id":"NLD.14_1","name":"Zuid-Holland","bounds":{"min":{"lng":3.8397,"lat":51.6439},"max":{"lng":5.036,"lat":52.3277}},"geojson_properties":{"GID_1":"NLD.14_1","GID_0":"NLD","COUNTRY":"Netherlands","NAME_1":"Zuid-Holland","VARNAME_1":"NA","NL_NAME_1":"NA","TYPE_1":"NA","ENGTYPE_1":"NA","CC_1":"NA","HASC_1":"NA","ISO_1":"NA"}}]
